---
- hosts: webservers
  become: yes
  vars:
    myvar1: naresh
    myvar2: pavan
  tasks:
  - name: display myvar1
    debug:
      msg: "{{myvar1}}"

  - name: display myvar2
    debug:
      msg: "{{myvar2}}"    